# Support the author by using the funding links below
# Developed and maintained by Waren Gonzaga with the help of awesome contributors.
# GitHub Sponsors: https://github.com/sponsors/warengonzaga
# Buy Me a Coffee: https://buymeacoffee.com/warengonzaga

github: warengonzaga
buy_me_a_coffee: warengonzaga

# Your support means a lot to me to continue the development of open source project like this.
# Sponsoring this project means a lot to me. Your support helps me to continue building great open-source projects just like this.